name: Build & Publish Transcriber image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # 2) setup buildx (по умолчанию драйвер docker, будет использовать кеш образов на runner)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) очищаем кеш сборок BuildKit, а не весь Docker-хост
      - name: Prune old BuildKit cache
        run: docker builder prune --all --force

      # 4) login в GHCR (нужен для push образа и для кеша в registry)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) build & push с кэшированием в registry
      - name: Build and push Transcriber image
        uses: docker/build-push-action@v3
        with:
          context: Transcriber
          file: Transcriber/Dockerfile
          push: true
          tags: |
            ghcr.io/sinoosoida/audio-data-parser:latest
            ghcr.io/sinoosoida/audio-data-parser:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/sinoosoida/audio-data-parser:cache
          cache-to: type=registry,ref=ghcr.io/sinoosoida/audio-data-parser:cache,mode=max
